repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      entry: black --line-length 80 pycse

# turn this on later. There is a lot of work to do...      
# -   repo: https://gitlab.com/pycqa/flake8
#    rev: 4.0.1
#    hooks:
#    - id: flake8
#      entry: flake8 --max-line-length 80 pycse

  - repo: local
    hooks:
    - id: nosetest
      name: nosetests
      entry: nosetests
      language: python
      types: [python]
