name: Run pycse tests

on: 
  push:


jobs:
  build:
    name: nosetest
    runs-on: ubuntu-20.04
    timeout-minutes: 5    
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install numpy scipy matplotlib pandas IPython ipykernel nbconvert python-coveralls nose nose-cov coverage numdifftools joblib
          nosetests
          coverage run -m nose pycse
          coverage report -m --include=pycse/*
          

