name: Run pycse tests

on: 
  push:


jobs:
  build:
    name: pytest
    runs-on: ubuntu-20.04
    timeout-minutes: 5    
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install numpy scipy matplotlib pandas IPython ipykernel nbconvert python-coveralls pytest pytest-cov coverage numdifftools joblib pycse
          pytest
          coverage run -m pytest pycse
          coverage report -m --include=pycse/*
          

