name: Run pycse tests

on: 
  push:


jobs:
  build:
    name: nosetest
    runs-on: ubuntu-latest
    timeout-minutes: 5    
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install numpy scipy matplotlib pandas IPython ipykernel nbconvert python-coveralls nose nose-cov coverage
          nosetests -v --with-coverage
          coverage run -m nose pycse
          coverage report -m

      - name: Coverage comment
        id: coverage_comment
        uses: ewjoachim/python-coverage-comment-action@v2
        with:
          GITHUB_TOKEN: ${{ github.token }}
