name: Run pycse tests

on: 
  push:


jobs:
  build:
    name: nosetest
    runs-on: ubuntu-latest
    timeout-minutes: 5    
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install numpy scipy matplotlib pandas IPython ipykernel nbconvert python-coveralls nose nose-cov coverage
          nosetests -v --with-coverage
          coverage run -m nose pycse
          coverage report -m
          
      - uses: actions/checkout@v2
      - name: Coverage Badge
        uses: tj-actions/coverage-badge-py@v1.8
